### ISSUE TITLE
Independent save files for Infinite Pit mod

### ISSUE THREAD

**Issue by redyoshi49q** [jdaster64/ttyd-infinite-pit#3]
Since there are only four save slots within a Paper Mario: TTYD save file, and especially since the Infinite Pit mod's saves would presumably always be entirely incompatible with vanilla save files, I think it would be useful if there was a way for the mod to use its own save data rather than that of the Paper Mario: TTYD in the physical or emulated Gamecube memory card.  This would reduce or eliminate the need to manually change between different memory card saves if someone were to want to have multiple Infinite Pit save slots without having to delete slots containing vanilla Paper Mario: TTYD save data.

I don't know how technically feasible this feature would be to implement; I'm putting forward the idea in case it might be either trivial enough to implement easily or wanted enough to implement in spite of the related technical hurdles.

**Comment by jdaster64** [comment]
It's a fair question; I'm going to have to decline because it's not really technically feasible.  Gamecube saves are tied to a type of game by default (e.g. US TTYD), not individual copies / variants, and changing it such that both Infinite Pit and vanilla TTYD would know to load different files would take a substantial amount of work.  In addition, the preferred of the two ways of loading the mod's code already requires the use of a vanilla-compatible save file with one save slot hacked, meaning it's most convenient to use a separate save from whatever one might use when playing vanilla anyway.

On Dolphin, it's already fairly trivial to swap save files out using the Memcard Manager / your OS's filesystem, and on console, particularly if you use an emulated memcard, it's not too much harder using similar methods.
